### ISSUE TITLE
佬要不加个群主/管理员删不了主人的问答的功能？

### ISSUE THREAD

**Issue by XiaoFuOS** [azmiao/XQA#11]
有时候设置的问答被群主或者管理员删力QAQ

**Comment by azmiao** [comment]
emmm，可惜我当初做的时候就是设计的允许删除的，所以存储格式就定死了，如果你需要可能需要你自己手动改了，比如把自己设置的问答全部放到一个host的键值对下面，XQA存储数据格式是用json的，你可以用代码取出数据来看看
