### ISSUE TITLE
要将图片按base64格式发出来要怎么改

### ISSUE THREAD

**Issue by duoshoumiao** [azmiao/XQA#12]
rt

**Comment by azmiao** [comment]
可参考露宝改的：https://github.com/morarity123/XQA

**Comment by duoshoumiao** [comment]
> 可参考露宝改的：https://github.com/morarity123/XQA

意思是直接下露宝的就行吗emmmm

**Comment by azmiao** [comment]
> > 可参考露宝改的：https://github.com/morarity123/XQA
> 
> 意思是直接下露宝的就行吗emmmm

应该可以的，他说他要改一个，应该能用，我暂时不需要就没测试

**Comment by duoshoumiao** [comment]
> > > 可参考露宝改的：https://github.com/morarity123/XQA
> > 
> > 意思是直接下露宝的就行吗emmmm
> 
> 应该可以的，他说他要改一个，应该能用，我暂时不需要就没测试

最近做kookbot一直需要这个64

**Comment by duoshoumiao** [comment]
> > > 可参考露宝改的：https://github.com/morarity123/XQA
> > 
> > 意思是直接下露宝的就行吗emmmm
> 
> 应该可以的，他说他要改一个，应该能用，我暂时不需要就没测试

用base64也发不到kook频道很烦不知道问题。

**Comment by azmiao** [comment]
> > > > 可参考露宝改的：https://github.com/morarity123/XQA
> > > 
> > > 
> > > 意思是直接下露宝的就行吗emmmm
> > 
> > 
> > 应该可以的，他说他要改一个，应该能用，我暂时不需要就没测试
> 
> 用base64也发不到kook频道很烦不知道问题。

kook的bot我倒是没用过，那玩意我就纯当语音软件的，虽然它越做越垃圾但主要还是得用它

**Comment by duoshoumiao** [comment]
> > > > > 可参考露宝改的：https://github.com/morarity123/XQA
> > > > 
> > > > 
> > > > 意思是直接下露宝的就行吗emmmm
> > > 
> > > 
> > > 应该可以的，他说他要改一个，应该能用，我暂时不需要就没测试
> > 
> > 用base64也发不到kook频道很烦不知道问题。
> 
> kook的bot我倒是没用过，那玩意我就纯当语音软件的，虽然它越做越垃圾但主要还是得用它

设置了全群问答，到了kook就都不见了。kook还不能设置图片问答

**Comment by azmiao** [comment]
kook也支持ob协议吗？

**Comment by duoshoumiao** [comment]
> kook也支持ob协议吗？

不知道诶，有没有可以编辑db.sqlite的软件，主要是插件好像无法把kook频道识别成群，虽然后台能看到群号

**Comment by azmiao** [comment]
> > kook也支持ob协议吗？
> 
> 不知道诶，有没有可以编辑db.sqlite的软件，主要是插件好像无法把kook频道识别成群，虽然后台能看到群号

你看util里面有读取方法可以读取内容的，这个我记得当时是做成json写入sqlite的

**Comment by duoshoumiao** [comment]
> > > kook也支持ob协议吗？
> > 
> > 不知道诶，有没有可以编辑db.sqlite的软件，主要是插件好像无法把kook频道识别成群，虽然后台能看到群号
> 
> 你看util里面有读取方法可以读取内容的，这个我记得当时是做成json写入sqlite的

我去看看
