### ISSUE TITLE
能否在增加对成功设置问题后机器人的回复的设置

### ISSUE THREAD

**Issue by ragnarok6324** [azmiao/XQA#13]
您好，腾讯这几个月封控机器人的力度越来越强，经常在连续设置问题的时候，设着设着就被封控了
是不是因为连续设置问题的时候，机器人复读“好的我记住了”被检测bot了呢？
如果是的话，请问能否在util.py中设置成功增加问题后机器人的回复，比如可以随机回复或者不回复，只在后台显示？
谢谢！

**Comment by azmiao** [comment]
风控这种东西不好说的，腾讯现在应该主要还是用的深度学习来检测的，至少大伙看来机器人说话频次突然增高就容易触发风控，另外也要看号，我自己的机器人也用了五六年了。

回复消息的话，你可以直接在`__init__.py`中116行那里简单修改下代码，修改设置问题后的回复或者不回复

**Comment by ragnarok6324** [comment]
> 回复消息的话，你可以直接在`__init__.py`中116行那里简单修改下代码，修改设置问题后的回复或者不回复

明白了，谢谢！

**Comment by azmiao** [comment]
issue先关了，有问题可以再开
