### ISSUE TITLE
Napcat端由于图片缓存格式不同导致无法正常设置问题

### ISSUE THREAD

**Issue by ragnarok6324** [azmiao/XQA#15]
设置带图片的回复后，bot并不回复该问题。
![1](https://github.com/user-attachments/assets/1a0a7aed-c683-41c2-a8b9-ff63ac468c2b)

hoshino后台日志
![image](https://github.com/user-attachments/assets/e5be6d68-59a6-4aeb-8089-c18a97c57502)

Napcat后台日志
2024-08-25 23:34:58 [ [32mINFO [39m] 芬里尔(438980368) | 群[尔威希、739039361、木华 陽、芬里尔(463922023)] 739039361(739039361): 开始测试
2024-08-25 23:35:02 [ [32mINFO [39m] 芬里尔(438980368) | 群[尔威希、739039361、木华 陽、芬里尔(463922023)] 739039361(739039361): 全群问这是一个
问题你答
 [图片|https://gchat.qpic.cn/gchatpic_new/739039361/3953922023-2935700190-2A775A7BC55EABDA3BD8D99697B3A993/0?term=255&is_o
rigin=0]
2024-08-25 23:35:03 [ [91mERROR [39m] 芬里尔(438980368) | 发生错误 Error: file not found
    at GetImage._handle (file:///C:/Users/Administrator/Desktop/%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%A0%E7%9A%84%E6%9C%BA%E
5%99%A8%E4%BA%BA%E7%99%BB%E9%99%86/NapCat-new/NapCat.win32.x64/napcat.mjs:24445:11)
    at async GetImage.websocketHandle (file:///C:/Users/Administrator/Desktop/%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%A0%E7%9A
%84%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%99%BB%E9%99%86/NapCat-new/NapCat.win32.x64/napcat.mjs:21764:23)
    at async ReverseWebsocket.onmessage (file:///C:/Users/Administrator/Desktop/%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%A0%E7%
9A%84%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%99%BB%E9%99%86/NapCat-new/NapCat.win32.x64/napcat.mjs:27137:28)
    at async WebSocket.<anonymous> (file:///C:/Users/Administrator/Desktop/%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%A0%E7%9A%84
%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%99%BB%E9%99%86/NapCat-new/NapCat.win32.x64/napcat.mjs:27177:7)
2024-08-25 23:35:03 [ [32mINFO [39m] 芬里尔(438980368) | 发送消息 给群聊 群[尔威希、739039361、木华 陽、芬里尔(463922023)] : 好的我记住了
2024-08-25 23:35:11 [ [32mINFO [39m] 芬里尔(438980368) | 群[尔威希、739039361、木华 陽、芬里尔(463922023)] 739039361(739039361): 这是一个问题

2024-08-25 23:35:11 [ [91mERROR [39m] 芬里尔(438980368) | 发生错误 Error: file not found
    at GetImage._handle (file:///C:/Users/Administrator/Desktop/%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%A0%E7%9A%84%E6%9C%BA%E
5%99%A8%E4%BA%BA%E7%99%BB%E9%99%86/NapCat-new/NapCat.win32.x64/napcat.mjs:24445:11)
    at async GetImage.websocketHandle (file:///C:/Users/Administrator/Desktop/%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%A0%E7%9A
%84%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%99%BB%E9%99%86/NapCat-new/NapCat.win32.x64/napcat.mjs:21764:23)
    at async ReverseWebsocket.onmessage (file:///C:/Users/Administrator/Desktop/%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%A0%E7%
9A%84%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%99%BB%E9%99%86/NapCat-new/NapCat.win32.x64/napcat.mjs:27137:28)
    at async WebSocket.<anonymous> (file:///C:/Users/Administrator/Desktop/%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%A0%E7%9A%84
%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%99%BB%E9%99%86/NapCat-new/NapCat.win32.x64/napcat.mjs:27177:7)
2024-08-25 23:35:11 [ [91mERROR [39m] 芬里尔(438980368) | 发生错误 Error: ENOENT: no such file or directory, open 'C:\Users\Adm
inistrator\Desktop\Resources\img\xqa\img\{2A775A7B-C55E-ABDA-3BD8-D99697B3A993}.png'

**Comment by azmiao** [comment]
麻烦尝试一下将`util.py`中122行开始的doing_img函数替换为如下：
```python
async def doing_img(bot, img: str, is_ans: bool = False, save: bool = False) -> str:
    img_path = os.path.join(FILE_PATH, 'img/')
    if save:
        logger.info('开始调用get_image接口获取图片信息')
        img_url = await bot.get_image(file=img)
        logger.info('图片信息接口返回：' + str(img_url))
        file = os.path.join(img_path, img)
        if not os.path.isfile(img_path + img):
            urllib.request.urlretrieve(url=img_url['url'], filename=file)
            logger.critical(f'XQA: 已下载图片{img}')
    if is_ans:  # 保证保存图片的完整性，方便迁移和后续做操作
        return 'file:///' + os.path.abspath(img_path + img)
    return img
```
之后再发送一次设置问题，然后截图一下hoshino的日志我看看napcat的接口返回的啥，只需要hoshino的日志就行

**Comment by ragnarok6324** [comment]
![image](https://github.com/user-attachments/assets/4af70797-b69a-4848-b622-df6f2abb1b44)
![image](https://github.com/user-attachments/assets/1a499c58-4f0e-4f1e-8355-2951c998da1a)

**Comment by azmiao** [comment]
看起来napcat接口请求出错了，但我看他们的文档是支持的
![image](https://github.com/user-attachments/assets/5edd4c43-1b7a-4e90-a774-c05f885b7fa7)

你看看你那边是否需要更新一下napcat？

**Comment by ragnarok6324** [comment]
![image](https://github.com/user-attachments/assets/6901622d-b102-4b72-95ff-757c1fcb5f22)
已安装Napcat的最新版本v2.2.12，似乎还是不行

**Comment by azmiao** [comment]
那我这没法解决了欸，你可以尝试携带napcat的日志去那边问问get_image这个接口现在正常不

**Comment by azmiao** [comment]
看napcat的get_file接口炸了，可以去问问get_image接口是不是也炸了
![image](https://github.com/user-attachments/assets/82ed02c2-5778-44e4-a2bb-e5001d5d9661)

**Comment by azmiao** [comment]
mark一手便于后续跟进
[napcat issue 313](https://github.com/NapNeko/NapCatQQ/issues/313)

**Comment by azmiao** [comment]
你在`utils.py`中搜索下这行：
```python
raw_body = raw_body if '.' in raw_body else raw_body + '.image'
```
然后直接吧这行删掉再试试

**Comment by ragnarok6324** [comment]
> 你在`utils.py`中搜索下这行：
> 
> ```python
> raw_body = raw_body if '.' in raw_body else raw_body + '.image'
> ```
> 
> 然后直接吧这行删掉再试试

![1](https://github.com/user-attachments/assets/03ca453e-9834-4515-9c35-e5bb2644f30a)
![2](https://github.com/user-attachments/assets/14a0d01f-11b5-4716-b127-ee453abceff3)

**Comment by azmiao** [comment]
我去，他这接口返回的URL怎么变成路径了。。。。

**Comment by ragnarok6324** [comment]
![1](https://github.com/user-attachments/assets/4c506ce9-3bbe-4592-b3cc-04ae4cd883e5)
![2](https://github.com/user-attachments/assets/235e5c6c-4070-4832-aa94-90f667eca60a)
这是2.2.36下，我把您告诉我删掉的那行恢复后运行的日志，需不需要删掉后再发送日志给你看看呢

**Comment by azmiao** [comment]
> ![1](https://private-user-images.githubusercontent.com/78748438/363498600-4c506ce9-3bbe-4592-b3cc-04ae4cd883e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDMwNjgsIm5iZiI6MTcyNTIwMjc2OCwicGF0aCI6Ii83ODc0ODQzOC8zNjM0OTg2MDAtNGM1MDZjZTktM2JiZS00NTkyLWIzY2MtMDRhZTRjZDg4M2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE0NTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NjYwOTg1MTYzZGE4NWEzNGVjZDZlM2QxODI1YjRkMzNkMGI4NzZjZjYyYjg0NzM4YmQzMjUyOTQzMGFlMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pXIF4jKfmjhXwS5u7Oeu0gvKj4oJ4bnPY9fhBpRxhXU) ![2](https://private-user-images.githubusercontent.com/78748438/363498602-235e5c6c-4070-4832-aa94-90f667eca60a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDMwNjgsIm5iZiI6MTcyNTIwMjc2OCwicGF0aCI6Ii83ODc0ODQzOC8zNjM0OTg2MDItMjM1ZTVjNmMtNDA3MC00ODMyLWFhOTQtOTBmNjY3ZWNhNjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE0NTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NjFkOWY2MGIwYTFmZmMwOThlY2IyYjFmMDViYThhN2I5MTJlYzdmMDAxMTJiNzM5ZDgzZTIzNWM1MTAyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CVixBHYtBsoPe70POTPA3g_oQx5X-j44Bv-7gH7y5BA) 这是2.2.36下，我把您告诉我删掉的那行恢复后运行的日志，需不需要删掉后再发送日志给你看看呢

需要删掉的，你用napcat之后应该都需要删掉那行

**Comment by ragnarok6324** [comment]
![1](https://github.com/user-attachments/assets/46c39a02-ff21-4b4b-af72-e84466783037)
![2](https://github.com/user-attachments/assets/16c01a9d-8f09-4fef-bd72-17cbad7329f6)
![3](https://github.com/user-attachments/assets/7a50a3dc-4ddc-463d-8914-dbec194ca308)
![4](https://github.com/user-attachments/assets/11d3a948-8eca-49e9-9ed0-1058d2e093a3)
删掉后运行的日志

**Comment by azmiao** [comment]
看来是文件名不合法，我看看咋改

**Comment by azmiao** [comment]
更新下试试？

**Comment by ragnarok6324** [comment]
感谢！已能成功下载图片并回复问题
![image](https://github.com/user-attachments/assets/161bc5d5-8bce-4de8-b2f5-5feb24e503d4)
![1](https://github.com/user-attachments/assets/c5b79f1d-8e14-4aff-bcf9-0194c2349b07)

**Comment by azmiao** [comment]
ok
