### ISSUE TITLE
旧eqa转过来的问答触发时报错

### ISSUE THREAD

**Issue by Mei-Sakura** [azmiao/XQA#16]
经典环节之修了一个bug出更多的bug
![image](https://github.com/user-attachments/assets/73192a65-9bd2-4b87-8a5a-6b9e10eee2c8)

**Comment by azmiao** [comment]
![image](https://github.com/user-attachments/assets/65fbe206-5dd4-4095-8187-5cd0d88e1cc4)
如图，NapCat接口已变动，已无法支持旧的图片再转换查询

**Comment by azmiao** [comment]
> ![image](https://private-user-images.githubusercontent.com/54100327/364718060-65fbe206-5dd4-4095-8187-5cd0d88e1cc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1Mjk4OTgsIm5iZiI6MTcyNTUyOTU5OCwicGF0aCI6Ii81NDEwMDMyNy8zNjQ3MTgwNjAtNjVmYmUyMDYtNWRkNC00MDk1LTgxODctNWNkMGQ4OGUxY2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA5NDYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNjhhZmMyNGI0NDNlMzI2ZTk1Y2U3MTBlNGZjNjE1NDk4NWEwNzQ3YWYzZmFjNzU4YWRlOGY1NzIzZWEyYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eIpWsRiaWjI_C7Tw7nr4X9cCiOYQ21scZfcOgyk7hy0) 如图，NapCat接口已变动，已无法支持旧的图片再转换查询

需要转换请确保napcat>2.2.36时使用的eqa

**Comment by azmiao** [comment]
由于napcat接口随ntqq变化，可能经常导致类似问题，因此如果可以的话仍推荐使用gocqhttp，另外可尝试将`__ini__.py`的第244行的`save=True`换成`save=False`，会降低部分情况下的稳定性，但可能能解决部分类似问题

**Comment by azmiao** [comment]
先关闭issue了，后续有问题可以再开

**Comment by azmiao** [comment]
已将补齐保存逻辑去除合并，可以尝试更新试试，commit d8953c2d910bbd7d7580ece5626572eadd62eecd

**Comment by Mei-Sakura** [comment]
> 已将补齐保存逻辑去除合并，可以尝试更新试试，commit [d8953c2](https://github.com/azmiao/XQA/commit/d8953c2d910bbd7d7580ece5626572eadd62eecd)

可以解决旧问答的报错。

另外如果设置新的问答会导致导入过来的旧问答无法触发，同时删除新问答时也会导致旧问答一同被删除
![image](https://github.com/user-attachments/assets/1486bc31-819e-49cc-9dd9-2d6ebe16e4c5)

**Comment by azmiao** [comment]
本项目设置新的问答的策略就是覆盖，所以删除的时候也会删掉
