### ISSUE TITLE
关于原eqa和现xqa的一些问题

### ISSUE THREAD

**Issue by 1055169799** [azmiao/XQA#2]
原eqa中，机器人管理员设置的问题，是可以在所有群内使用的，但是转移过后，就变成了下达转移命令的那个群才能使用，如果要在其它群使用，还要在每个群内发送复制命令，未免有些繁琐了。

**Comment by azmiao** [comment]
这确实没办法，因为原本数据存的就是没有群标签的，所以只能这样迁移
