### ISSUE TITLE
可以注入吗，建议加个计时器，用于指定时间执行指令和回复

### ISSUE THREAD

**Issue by damemod** [azmiao/XQA#5]

**Comment by damemod** [comment]
cron:https://github.com/Tivix/django-cron

**Comment by damemod** [comment]
runcode:https://github.com/CMHopeSunshine/codeonline

**Comment by azmiao** [comment]
定时器的话我建议直接写个定时任务插件之类的，感觉实在没有必要通过问答注入，可能含有一定风险。

**Comment by damemod** [comment]
可以通过设置注入权限来解决，而已知的插件一般都是安全的，分两种，如我问***你执行(已有插件的指令),以上runcode的指令另算一种，因为可能有风险，这样就可以对于你执行的关键词，分别设置所需权限.而计时器可以对已有插件和话语进行定时输出(可以设置权限)。可以更加的灵活,但前提是插件之间能做到相互调用

**Comment by azmiao** [comment]
我还是觉得没有必要，这样不如直接设定时任务来的方便，而且动态调用不太好实现，然后问答方式添加定时的话参数量也非常大，cron表达式还是有点长的，需要的参数也不少。所以如果真需要群里手动设置闹钟之类的可以自己写个设置闹钟的插件，也非常简单省力

**Comment by damemod** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
