### ISSUE TITLE
维护组提供的问答可否参考eqa

### ISSUE THREAD

**Issue by yuuki-nya** [azmiao/XQA#7]
XQA的维护组全群问答似乎是把bot的glist遍历一次然后分别加上这个问答，这么做有几个问题：
1. 多gocqhttp接入的情况，只能获取当前bot的glist，其他bot的群无法获取，这点可以修改 get_g_list 函数解决；
2. 维护租设置的问答后新加入的群无法获取这个问答;
3. 维护组的全群问题必须用搜索，如果问的问题多了，不好维护。

综上所述，可否考虑参考xqa的维护组的“有人问”命令，单独作为一个问答数据存在数据库，所有群默认加载这组数据，也方便维护。

**Comment by azmiao** [comment]
+ 1.待确认后修复。
+ 2.本XQA逻辑初衷就是和eqa不一样，【本XQA希望最大程度上满足设置的自由度】，全群问只是方便维护组设置通用问题，然后不需要的群可以自己去群里再单独删。而你的这个问题可以采用复制问答命令+增减一些问答来解决，虽然麻烦了点，但感觉比下面这几个问题好解决。
+ 3.搜索这一块，我觉得可以不用强制吧，嫌消息长了就可以自己去搜索，或者加分片或者转发消息。

### 另外，如果单独做个维护组的数据库，那么可能导致的问题：
+ 1.设置所有群的问题，但某几个群不需要，就无法单独删除，除非单独再做维护组的分群删除功能。但是这样和单独每个群设置有人问不就一样了吗。
+ 2.理论上，维护组设置的问题就无法被其他人覆盖，但是如果某个群里的管理希望改变这个问答就改不了，和初衷相违背
+ 3.优先级上，是优先回答个人问，再有人问的，有人问是管理设置给大家看的，如果个人不想看可以设置个人问答来不看。但维护组单独的问答肯定要最高优先级啊，这样也和初衷相违背
+ 4.另外补充一下吧，本XQA不是像小栗子的词库一样作为索引查找使用的，而是希望和lan佬的闭源xqa类似，让群友玩出各种花样，~~顺便还能让群友学学正则表达式~~

**Comment by azmiao** [comment]
话说你要获取所有bot的群干啥，正常不应该就是用哪个bot获取哪个bot的内容吗，然后多cq接入的时候只相应接受命令的那个bot这样吗

**Comment by yuuki-nya** [comment]
> 

因为风控的原因，我现在个gocq同时接入一个hoshino并分流群，我在bot 1的群发布了全群问答，除bot 1所在的群都没有这个问答，所以g_list我改为这种
`for sid in hoshino.get_self_ids():
    gl = await bot.get_group_list(self_id=sid)
    gl = [g['group_id'] for g in gl]`
当然这个只是个人需求，你可以考虑要不要加上

**Comment by azmiao** [comment]
> 

这是正常的，只会添加Bot所在的几个群，不能添加其他bot的群，不然多cq接入的时候全局加会炸的，所以要改不能单单只改这个，单改这个也会炸的，而且为了分bot控制还得单独加好几个命令来防止加错，得不偿失了。所以我建议还是保持原样，不然需要的改动太大了
