### ISSUE TITLE
复制问答提示群号错误

### ISSUE THREAD

**Issue by Xruoji** [azmiao/XQA#9]
![QD5326O)XOT6Q1PS(83SS$F](https://user-images.githubusercontent.com/112480168/206433458-e7a8effd-519a-4287-a765-a6d72281d100.png)
![BZXLUG5GF}G{GK4%0$KUV 9](https://user-images.githubusercontent.com/112480168/206433508-fe91bff4-02f0-4709-8a47-704ff0aeab2e.png)
大佬，救救，群被封了转移下问答

**Comment by azmiao** [comment]
哦，群号被封了后，检测不到被封的群了，校验群号失败了，你可以尝试把`__init__.py`中的197-199行临时注释掉
```
    group_list = await get_g_list(bot)
    if (group_1 not in group_list) or (group_2 not in group_list):
        await bot.finish(ev, f'群号输入错误！请检查')
```

**Comment by azmiao** [comment]
哦对了该功能目前仅支持转移有人问，不支持转移个人问答

**Comment by azmiao** [comment]
> 哦对了该功能目前仅支持转移有人问，不支持转移个人问答

我给你改一下吧，你稍等

**Comment by Xruoji** [comment]
佬，是这样的。注释掉那三行后，我用多个群进行尝试。只有最开始那个群提示成功但实际发看看有人问还是没内容，别的群复制后有人问就复制上了。




&nbsp;


Teriri
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月8日(星期四) 晚上7:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [azmiao/XQA] 复制问答提示群号错误 (Issue #9)





  
哦对了该功能目前仅支持转移有人问，不支持转移个人问答
  
我给你改一下吧，你稍等

**Comment by Xruoji** [comment]
注释掉可以了，感谢！

**Comment by azmiao** [comment]
a640bdaaa2fc60a7d1f405b9fdf20d9b28c9ae1c 中调整了命令，现在可以选择：只复制有人问/只复制个人问答/复制全部问答

**Comment by azmiao** [comment]
当然，群被封了还是得注释掉那三行代码去除校验
